// Get the contact details from API
export const UPDATE_CONTACTS = 'UPDATE_CONTACTS';

//Add new contact
export const ADD_CONTACT = 'ADD_CONTACT';

export const EDIT_CONTACT_SUCCESSFUL = 'EDIT_CONTACT_SUCCESSFUL';
export const EDIT_CONTACT_FAILED = 'EDIT_CONTACT_FAILED';


export const DELETE_CONTACT_SUCCESSFUL = 'DELETE_CONTACT_SUCCESSFUL';
export const DELETE_CONTACT_FAILED = 'DELETE_CONTACT_FAILED';


